name: Tutt-Home
description: They are nothing before me...
meta_description: "Viết những gì mình thích"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://trnthanhtu.github.io'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://trnthanhtu.github.io'
author:         'Trần Thanh Tú'
