name: Tutt-Home
description: Viết những gì mình thích. Lượm lặt những gì mình nghe. Ghi nhớ những gì mình đọc
meta_description: "Viết những gì mình thích"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://trnthanhtu.github.io'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://trnthanhtu.github.io'
author:         'Trần Thanh Tú'
